# Generated by Django 5.2.6 on 2026-01-28 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autoevaluacion',
            fields=[
                ('id_autoevaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'autoevaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id_competencia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_competencia', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'competencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id_dimension', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_dimension', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'dimension',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionJefatura',
            fields=[
                ('id_evaluacion_jefatura', models.IntegerField(primary_key=True, serialize=False)),
                ('puntaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_evaluacion', models.DateField()),
                ('momento_evaluacion', models.DateTimeField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluacion_jefatura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NivelJerarquico',
            fields=[
                ('id_nivel_jerarquico', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_nivel_jerarquico', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'nivel_jerarquico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextosEvaluacion',
            fields=[
                ('id_textos_evaluacion', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_excel', models.CharField(max_length=10, unique=True)),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'textos_evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido_paterno', models.CharField(max_length=40)),
                ('apellido_materno', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=80)),
                ('genero', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
    ]
