# Generated by Django 5.2.6 on 2026-02-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuestionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoConsolidado',
            fields=[
                ('id_resultado', models.AutoField(primary_key=True, serialize=False)),
                ('puntaje_autoev', models.DecimalField(decimal_places=2, max_digits=5)),
                ('puntaje_jefe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('diferencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom_competencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom_dimension', models.DecimalField(decimal_places=2, max_digits=5)),
                ('prom_general', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodo', models.IntegerField()),
                ('fecha_consolidacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resultado_consolidado',
                'managed': False,
            },
        ),
    ]
