-- =========================
-- Tabla Dimension
-- =========================
CREATE TABLE DIMENSION (
    ID_DIMENSION INT NOT NULL,
    NOMBRE_DIMENSION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DIMENSION)
);

-- =========================
-- Tabla Departamento
-- =========================
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO)
);

-- =========================
-- Tabla Nivel Jerarquico
-- =========================
CREATE TABLE NIVEL_JERARQUICO (
    ID_NIVEL_JERARQUICO INT NOT NULL,
    NOMBRE_NIVEL_JERARQUICO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Cargo (depende de Nivel Jerarquico)
-- =========================
CREATE TABLE CARGO (
    ID_CARGO INT NOT NULL,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_CARGO),
    CONSTRAINT CARGO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Trabajador (depende de Cargo, Nivel, Depto y Jefe)
-- =========================
CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR INT NOT NULL,
    RUT VARCHAR(20) NOT NULL,
    ID_JEFE_DIRECTO INT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    CARGO_ID_CARGO INT NOT NULL,
    DEPARTAMENTO_ID_DEPARTAMENTO INT NOT NULL,
    PRIMARY KEY (ID_TRABAJADOR),
    UNIQUE (RUT),
    CONSTRAINT TRABAJADOR_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT TRABAJADOR_CARGO_FK FOREIGN KEY (CARGO_ID_CARGO)
        REFERENCES CARGO(ID_CARGO),
    CONSTRAINT TRABAJADOR_DEPTO_FK FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT TRABAJADOR_JEFE_FK FOREIGN KEY (ID_JEFE_DIRECTO)
        REFERENCES TRABAJADOR(ID_TRABAJADOR)
);

-- =========================
-- Tabla Competencia (depende de Dimension)
-- =========================
CREATE TABLE COMPETENCIA (
    ID_COMPETENCIA INT NOT NULL,
    NOMBRE_COMPETENCIA VARCHAR(50) NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    PRIMARY KEY (ID_COMPETENCIA),
    CONSTRAINT COMPETENCIA_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION)
);

-- =========================
-- Tabla Textos Evaluacion (depende de Competencia y Nivel Jerarquico)
-- =========================
CREATE TABLE TEXTOS_EVALUACION (
    ID_TEXTOS_EVALUACION INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTO TEXT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TEXTOS_EVALUACION),
    UNIQUE (CODIGO_EXCEL),
    CONSTRAINT TEXTO_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA)
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT TEXTO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Autoevaluacion (depende de Trabajador y Textos Evaluacion)
-- =========================
CREATE TABLE AUTOEVALUACION (
    ID_AUTOEVALUACION INT NOT NULL,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_AUTOEVALUACION),
    CONSTRAINT AUTO_TRAB_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT AUTO_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL)
);

-- =========================
-- Tabla Evaluacion Jefatura (depende de Trabajador y Textos Evaluacion)
-- =========================
CREATE TABLE EVALUACION_JEFATURA (
    ID_EVALUACION_JEFATURA INT NOT NULL,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    EVALUADOR_ID_TRABAJADOR INT NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_EVALUACION_JEFATURA),
    CONSTRAINT JEF_TRAB_EVALUADO_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TRAB_EVALUADOR_FK FOREIGN KEY (EVALUADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL)
);