-- =========================
-- Recuerda, antes de iniciar MySql ingresa chcp 65001
-- para no tener problemas con los caracteres especiales
-- CREATE DATABASE sistema_mohala CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
-- USE sistema_mohala; SET NAMES 'utf8mb4'; 
-- =========================

-- =========================
-- Tabla Dimension
-- =========================
CREATE TABLE DIMENSION (
    ID_DIMENSION INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DIMENSION VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DIMENSION)
);

-- =========================
-- Tabla Departamento
-- =========================
CREATE TABLE DEPARTAMENTO (
    ID_DEPARTAMENTO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_DEPARTAMENTO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_DEPARTAMENTO)
);

-- =========================
-- Tabla Nivel Jerarquico
-- =========================
CREATE TABLE NIVEL_JERARQUICO (
    ID_NIVEL_JERARQUICO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_NIVEL_JERARQUICO VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Cargo
-- =========================
CREATE TABLE CARGO (
    ID_CARGO INT NOT NULL AUTO_INCREMENT,
    NOMBRE_CARGO VARCHAR(50) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_CARGO),
    CONSTRAINT CARGO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Trabajador
-- =========================
CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR INT NOT NULL AUTO_INCREMENT,
    RUT VARCHAR(20) NOT NULL,
    ID_JEFE_DIRECTO INT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    CARGO_ID_CARGO INT NOT NULL,
    DEPARTAMENTO_ID_DEPARTAMENTO INT NOT NULL,
    PRIMARY KEY (ID_TRABAJADOR),
    UNIQUE (RUT),
    CONSTRAINT TRABAJADOR_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO),
    CONSTRAINT TRABAJADOR_CARGO_FK FOREIGN KEY (CARGO_ID_CARGO)
        REFERENCES CARGO(ID_CARGO),
    CONSTRAINT TRABAJADOR_DEPTO_FK FOREIGN KEY (DEPARTAMENTO_ID_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO(ID_DEPARTAMENTO),
    CONSTRAINT TRABAJADOR_JEFE_FK FOREIGN KEY (ID_JEFE_DIRECTO)
        REFERENCES TRABAJADOR(ID_TRABAJADOR)
);

-- =========================
-- Tabla Competencia
-- =========================
CREATE TABLE COMPETENCIA (
    ID_COMPETENCIA INT NOT NULL AUTO_INCREMENT,
    NOMBRE_COMPETENCIA VARCHAR(50) NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    PRIMARY KEY (ID_COMPETENCIA),
    CONSTRAINT COMPETENCIA_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION)
        REFERENCES DIMENSION(ID_DIMENSION)
);

-- =========================
-- Tabla Textos Evaluacion
-- =========================
CREATE TABLE TEXTOS_EVALUACION (
    ID_TEXTOS_EVALUACION INT NOT NULL AUTO_INCREMENT,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTO TEXT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TEXTOS_EVALUACION),
    UNIQUE (CODIGO_EXCEL),
    CONSTRAINT TEXTO_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA)
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT TEXTO_NIVEL_FK FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO)
        REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

-- =========================
-- Tabla Autoevaluacion
-- =========================
CREATE TABLE AUTOEVALUACION (
    ID_AUTOEVALUACION INT NOT NULL AUTO_INCREMENT,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO_FINALIZACION BOOLEAN DEFAULT FALSE NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_AUTOEVALUACION),
    CONSTRAINT AUTO_TRAB_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT AUTO_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT UNIQUE_AUTO_TRAB_PREG UNIQUE (TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL)
);

-- =========================
-- Tabla Evaluacion Jefatura
-- =========================
CREATE TABLE EVALUACION_JEFATURA (
    ID_EVALUACION_JEFATURA INT NOT NULL AUTO_INCREMENT,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    EVALUADOR_ID_TRABAJADOR INT NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO_FINALIZACION BOOLEAN DEFAULT FALSE NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_EVALUACION_JEFATURA),
    CONSTRAINT JEF_TRAB_EVALUADO_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TRAB_EVALUADOR_FK FOREIGN KEY (EVALUADOR_ID_TRABAJADOR)
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT JEF_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL)
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    CONSTRAINT UNIQUE_JEFE_EVAL_PREG UNIQUE (EVALUADOR_ID_TRABAJADOR, TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL)
);

-- =========================
-- Tabla Resultado Consolidado (NUEVA)
-- =========================

CREATE TABLE RESULTADO_CONSOLIDADO (
    ID_RESULTADO INT NOT NULL AUTO_INCREMENT,
    PUNTAJE_AUTOEV DECIMAL(5,2) NOT NULL,
    PUNTAJE_JEFE DECIMAL(5,2) NOT NULL,
    DIFERENCIA DECIMAL(5,2) NOT NULL,
    PROM_COMPETENCIA DECIMAL(5,2) NOT NULL,
    PROM_DIMENSION DECIMAL(5,2) NOT NULL,
    PROM_GENERAL DECIMAL(5,2) NOT NULL,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    -- Control Temporal
    PERIODO INT NOT NULL,
    FECHA_CONSOLIDACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_RESULTADO),
    CONSTRAINT RES_TRAB_FK FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR) 
        REFERENCES TRABAJADOR(ID_TRABAJADOR),
    CONSTRAINT RES_DIM_FK FOREIGN KEY (DIMENSION_ID_DIMENSION) 
        REFERENCES DIMENSION(ID_DIMENSION),
    CONSTRAINT RES_COMP_FK FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA) 
        REFERENCES COMPETENCIA(ID_COMPETENCIA),
    CONSTRAINT RES_TEXTO_FK FOREIGN KEY (CODIGO_EXCEL) 
        REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL),
    
    -- Evita duplicidad: un resultado por pregunta, por trabajador, por año
    CONSTRAINT UNQ_RES_TRAB_PREG_PERIODO UNIQUE (TRABAJADOR_ID_TRABAJADOR, CODIGO_EXCEL, PERIODO)
);