CREATE TABLE DIMENSION (
    ID_DIMENSION INT NOT NULL,
    NOMBRE_DIMENSION VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_DIMENSION)
);

CREATE TABLE NIVEL_JERARQUICO (
    ID_NIVEL_JERARQUICO INT NOT NULL,
    NOMBRE_NIVEL_JERARQUICO VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID_NIVEL_JERARQUICO)
);

CREATE TABLE TRABAJADOR (
    ID_TRABAJADOR INT NOT NULL,
    RUT VARCHAR(20) NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO_PATERNO VARCHAR(40) NOT NULL,
    APELLIDO_MATERNO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    DEPARTAMENTO VARCHAR(40) NOT NULL,
    CARGO VARCHAR(40) NOT NULL,
    GENERO VARCHAR(10) NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TRABAJADOR),
    FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO) REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

CREATE TABLE COMPETENCIA (
    ID_COMPETENCIA INT NOT NULL,
    NOMBRE_COMPETENCIA VARCHAR(30) NOT NULL,
    DIMENSION_ID_DIMENSION INT NOT NULL,
    PRIMARY KEY (ID_COMPETENCIA),
    FOREIGN KEY (DIMENSION_ID_DIMENSION) REFERENCES DIMENSION(ID_DIMENSION)
);

CREATE TABLE TEXTOS_EVALUACION (
    ID_TEXTOS_EVALUACION INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    TEXTO TEXT NOT NULL,
    COMPETENCIA_ID_COMPETENCIA INT NOT NULL,
    NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO INT NOT NULL,
    PRIMARY KEY (ID_TEXTOS_EVALUACION),
    UNIQUE (CODIGO_EXCEL),
    FOREIGN KEY (COMPETENCIA_ID_COMPETENCIA) REFERENCES COMPETENCIA(ID_COMPETENCIA),
    FOREIGN KEY (NIVEL_JERARQUICO_ID_NIVEL_JERARQUICO) REFERENCES NIVEL_JERARQUICO(ID_NIVEL_JERARQUICO)
);

CREATE TABLE AUTOEVALUACION (
    ID_AUTOEVALUACION INT NOT NULL,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_AUTOEVALUACION),
    FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR),
    FOREIGN KEY (CODIGO_EXCEL) REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL)
);

CREATE TABLE EVALUACION_JEFATURA (
    ID_EVALUACION_JEFATURA INT NOT NULL,
    PUNTAJE DECIMAL(5,2) NOT NULL,
    EVALUADOR VARCHAR(50) NOT NULL,
    FECHA_EVALUACION DATE NOT NULL,
    MOMENTO_EVALUACION TIMESTAMP NOT NULL,
    COMENTARIO TEXT,
    TRABAJADOR_ID_TRABAJADOR INT NOT NULL,
    CODIGO_EXCEL VARCHAR(10) NOT NULL,
    PRIMARY KEY (ID_EVALUACION_JEFATURA),
    FOREIGN KEY (TRABAJADOR_ID_TRABAJADOR) REFERENCES TRABAJADOR(ID_TRABAJADOR),
    FOREIGN KEY (CODIGO_EXCEL) REFERENCES TEXTOS_EVALUACION(CODIGO_EXCEL)
);
